version: '3.6'

services:
  database:
    image: "postgres:11.1-alpine"
    restart: always
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=interadmin
      - POSTGRES_PASSWORD=interpassword
      - POSTGRES_DB=interdb
    volumes: 
            - ./docker-pg-init.sql:/docker-entrypoint-initdb.d/docker-pg-init.sql
    container_name: "pasticceria_database"